/// <summary>A risk alert generated by a detection routine. Central transactional table.</summary>
table 50101 "RIA Risk Alert"
{
    Caption = 'RIA Risk Alert';
    DataClassification = CustomerContent;
    LookupPageId = "RIA Risk Alerts";
    DrillDownPageId = "RIA Risk Alerts";

    fields
    {
        field(1; "Entry No."; Integer)
        {
            Caption = 'Entry No.';
            AutoIncrement = true;
        }
        field(2; "Control ID"; Code[20])
        {
            Caption = 'Control ID';
            TableRelation = "RIA Control Catalogue"."Control ID";
        }
        field(3; "Control Name"; Text[100])
        {
            Caption = 'Control Name';
        }
        field(4; Layer; Enum "RIA Layer")
        {
            Caption = 'Layer';
        }
        field(5; Domain; Enum "RIA Domain")
        {
            Caption = 'Domain';
        }
        field(6; Severity; Enum "RIA Severity")
        {
            Caption = 'Severity';
        }
        field(7; "Risk Score"; Decimal)
        {
            Caption = 'Risk Score';
            DecimalPlaces = 1 : 1;
            MinValue = 0;
            MaxValue = 10;
        }
        field(8; Status; Enum "RIA Alert Status")
        {
            Caption = 'Status';
        }
        field(9; "Detected DateTime"; DateTime)
        {
            Caption = 'Detected';
            Editable = false;
        }
        field(10; "Title"; Text[150])
        {
            Caption = 'Title';
        }
        field(11; "Description"; Text[2048])
        {
            Caption = 'Description';
        }
        field(12; "Recommended Action"; Text[2048])
        {
            Caption = 'Recommended Action';
        }
        field(13; "Amount (LCY)"; Decimal)
        {
            Caption = 'Amount (LCY)';
            AutoFormatType = 1;
            AutoFormatExpression = '';
        }
        field(20; "Source Table No."; Integer)
        {
            Caption = 'Source Table No.';
        }
        field(21; "Source System ID"; Guid)
        {
            Caption = 'Source System Id';
        }
        field(22; "Source Document No."; Code[20])
        {
            Caption = 'Source Document No.';
        }
        field(23; "Source Document Type"; Text[50])
        {
            Caption = 'Source Document Type';
        }
        field(30; "Entity Type"; Enum "RIA Profile Type")
        {
            Caption = 'Entity Type';
        }
        field(31; "Entity No."; Code[20])
        {
            Caption = 'Entity No.';
        }
        field(32; "Entity Name"; Text[100])
        {
            Caption = 'Entity Name';
        }
        field(40; "Assigned To"; Code[50])
        {
            Caption = 'Assigned To';
            TableRelation = "User Setup"."User ID";
            ValidateTableRelation = false;
        }
        field(41; "Acknowledged By"; Code[50])
        {
            Caption = 'Acknowledged By';
            Editable = false;
        }
        field(42; "Acknowledged DateTime"; DateTime)
        {
            Caption = 'Acknowledged';
            Editable = false;
        }
        field(43; "Resolved By"; Code[50])
        {
            Caption = 'Resolved By';
            Editable = false;
        }
        field(44; "Resolved DateTime"; DateTime)
        {
            Caption = 'Resolved';
            Editable = false;
        }
        field(45; "Resolution Notes"; Text[2048])
        {
            Caption = 'Resolution Notes';
        }
        field(46; "SLA Due DateTime"; DateTime)
        {
            Caption = 'SLA Due';
            Editable = false;
        }
        field(47; "SLA Breached"; Boolean)
        {
            Caption = 'SLA Breached';
            Editable = false;
            ToolTip = 'Set by the SLA monitor job when an open alert passes its SLA Due date/time.';
        }
        field(50; "Case No."; Code[20])
        {
            Caption = 'Investigation Case No.';
            TableRelation = "RIA Investigation Case"."No.";
        }
        field(51; "Dedup Hash"; Text[100])
        {
            Caption = 'Deduplication Hash';
            ToolTip = 'Unique fingerprint used to prevent duplicate alerts for the same finding.';
        }
        field(60; "Has Evidence"; Boolean)
        {
            Caption = 'Has Evidence';
            FieldClass = FlowField;
            CalcFormula = exist("RIA Alert Evidence" where("Alert Entry No." = field("Entry No.")));
            Editable = false;
        }
        field(61; "Comment Count"; Integer)
        {
            Caption = 'Comments';
            FieldClass = FlowField;
            CalcFormula = count("RIA Alert Evidence" where("Alert Entry No." = field("Entry No.")));
            Editable = false;
        }
    }

    keys
    {
        key(PK; "Entry No.") { Clustered = true; }
        key(Status; Status, Severity, "Detected DateTime") { }
        key(Control; "Control ID", Status) { }
        key(Entity; "Entity Type", "Entity No.") { }
        key(Dedup; "Dedup Hash") { }
        key(Assigned; "Assigned To", Status) { }
        key(Domain; Domain, Severity) { }
    }

    fieldgroups
    {
        fieldgroup(DropDown; "Entry No.", Title, Severity, Status) { }
        fieldgroup(Brick; Title, Severity, "Amount (LCY)", "Detected DateTime", Status) { }
    }

    trigger OnInsert()
    begin
        if "Detected DateTime" = 0DT then
            "Detected DateTime" := CurrentDateTime();
    end;
}
